In [ ]:
import numpy as np
# np.__version__


'1.26.4'

In [7]:
lst = [1,2,3,4,5]
ar1 = np.array(lst)##this is the way to conver the list into array
ar1
# print(type(ar1))

array([1, 2, 3, 4, 5])

In [15]:
import numpy as np

arr2 = np.arange(1, 10)
print(arr2)


[1 2 3 4 5 6 7 8 9]


In [ ]:
arr3 = np.ones((2, 3))
print(arr3)##this is the creatoin of 2d arry


[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
arr5 = np.linspace(1,3,10)
arr5


array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [24]:
## converting 1d arry into 2d arry
arr6 = np.arange(1,31).reshape(5,6)##arrage function is used to make 1d array
## and the reshape is used to convert the arrary into differnt different shapes
arr6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [ ]:
arr7 = np.random.random(10)
arr7## this is how a random array is made

array([8.82761423e-01, 4.88535262e-04, 3.59264859e-01, 9.96278990e-01,
       1.98212171e-01, 1.73320349e-01, 9.95088011e-01, 3.65736187e-01,
       1.95255982e-01, 6.72876478e-01])

In [366]:
arr8 = np.arange(60).reshape(6, 10)
print(arr8.shape)
# ## this is how a 2d array is made
# print(arr8.dtype)
# print(arr8.size)
# print(arr8.ndim)
arr9 = arr8.T.shape
arr9



(6, 10)


(10, 6)

In [ ]:
arr7 = np.random.

In [362]:
arr8.ravel()
arr8.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [370]:
##indexing and slicing in arry
##starting from 1d arry
arr2 = np.arange(1, 10)
print(arr2)
print(arr2[1:4])##this is slicing
print(arr2[-1])## this is indexing



[1 2 3 4 5 6 7 8 9]
[2 3 4]
9


In [408]:
##this is how a 2d slicing is work in arry
# arr8[5:6,2:3][0][0]
arr8[::-1,::-1]



array([[ 59,  58,  57,  56,  55,  54,  53,  52,  51,  50],
       [ 49,  48,  47,  46,  45,  44,  43, 100,  41,  40],
       [ 39,  38,  37,  36,  35,  34,  33,  32,  31,  30],
       [ 29,  28,  27,  26,  25,  24,  23,  22,  21,  20],
       [ 19,  18,  17,  16,  15,  14,  13,  12,  11,  10],
       [  9,   8,   7,   6,   5,   4,   3,   2,   1,   0]])

In [418]:
## this is how a  3d matrix is done
arr10 = np.arange(225).reshape(3, 15, 5)  # 3 × 15 × 5 = 225
print(arr10)


[[[  0   1   2   3   4]
  [  5   6   7   8   9]
  [ 10  11  12  13  14]
  [ 15  16  17  18  19]
  [ 20  21  22  23  24]
  [ 25  26  27  28  29]
  [ 30  31  32  33  34]
  [ 35  36  37  38  39]
  [ 40  41  42  43  44]
  [ 45  46  47  48  49]
  [ 50  51  52  53  54]
  [ 55  56  57  58  59]
  [ 60  61  62  63  64]
  [ 65  66  67  68  69]
  [ 70  71  72  73  74]]

 [[ 75  76  77  78  79]
  [ 80  81  82  83  84]
  [ 85  86  87  88  89]
  [ 90  91  92  93  94]
  [ 95  96  97  98  99]
  [100 101 102 103 104]
  [105 106 107 108 109]
  [110 111 112 113 114]
  [115 116 117 118 119]
  [120 121 122 123 124]
  [125 126 127 128 129]
  [130 131 132 133 134]
  [135 136 137 138 139]
  [140 141 142 143 144]
  [145 146 147 148 149]]

 [[150 151 152 153 154]
  [155 156 157 158 159]
  [160 161 162 163 164]
  [165 166 167 168 169]
  [170 171 172 173 174]
  [175 176 177 178 179]
  [180 181 182 183 184]
  [185 186 187 188 189]
  [190 191 192 193 194]
  [195 196 197 198 199]
  [200 201 202 203 204]
  [205 206 2

In [427]:
arr11 = np.ones((3,4,5))##this is the aother way to create  3d  array in python
arr11[0:,1:4,2:4]


array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [436]:
np.max(arr8)
np.min(arr8)
np.mean(arr8)
np.median(arr8)
np.std(arr8)
arr8.sort()
arr8




array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  43,  44,  45,  46,  47,  48,  49, 100],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59]])

In [ ]:
arr11 = np.array([2,5,1,9])
arr11.argsort()